'use strict';
const galleries={packaging:[{src:'ire-gift-packaging',title:'마음을 담은 선물 포장',description:'보냉 상자와 선물 가방 포장 예시입니다. 세부 구성은 상담 시 안내해 드릴게요.'}],meals:[{src:'ire-dinner-illustration',title:'함께 먹는 삼겹살',description:'맛있는 한 끼를 위한 식탁 제안.'},{src:'ire-pork-belly-editorial',title:'오늘의 추천 부위, 삼겹살',description:'구이와 볶음으로 즐기는 고소한 맛.'},{src:'ire-jeyuk-editorial',title:'삼겹살 제육볶음',description:'매콤달콤한 양념으로 준비하는 오늘 저녁.'}],products:[{src:'ire-beef-editorial',title:'정성껏 담은 소고기 모둠',description:'판매 부위와 구성은 매장에 문의해 주세요.'},{src:'ire-beef-editorial',title:'한 점씩, 정갈하게',description:'원하시는 부위와 수량을 상담해 주세요.'},{src:'ire-gift-editorial',title:'마음을 전하는 선물',description:'구성 예시입니다. 가격과 수령 일정은 매장 상담으로 안내합니다.'}],craft:[{src:'ire-owner-editorial',title:'안녕하세요, 이레축산입니다',description:'호매실에서 만나는 우리 동네 정육점.'},{src:'ire-craft-editorial',title:'사장이 직접 손질합니다',description:'한 부위씩 정성껏 준비합니다.'}],store:[{src:'ire-storefront-entrance',title:'이레축산에서 만나요',description:'호매실 삼익2차 후문 앞. 사진은 개업 당시 모습입니다.'}]};
const modal=document.querySelector('#photo-modal'),photo=document.querySelector('#modal-image'),title=document.querySelector('#modal-title'),description=document.querySelector('#modal-description'),counter=document.querySelector('#modal-counter'),previous=document.querySelector('#modal-prev'),next=document.querySelector('#modal-next');
let gallery=[],index=0,opener=null,startX=null,startY=null;
function renderPhoto(){const item=gallery[index];photo.src=`/images/${item.src}.webp`;photo.alt=item.title;title.textContent=item.title;description.textContent=item.description;counter.textContent=`${String(index+1).padStart(2,'0')} / ${String(gallery.length).padStart(2,'0')}`;previous.disabled=next.disabled=gallery.length===1;}
function step(direction){index=(index+direction+gallery.length)%gallery.length;renderPhoto();}
document.querySelectorAll('.photo-open').forEach(button=>button.addEventListener('click',()=>{opener=button;gallery=galleries[button.dataset.gallery];index=Number(button.dataset.index);renderPhoto();modal.showModal();document.body.classList.add('modal-open');document.querySelector('#modal-close').focus();}));
document.querySelector('#modal-close').addEventListener('click',()=>modal.close());
modal.addEventListener('close',()=>{document.body.classList.remove('modal-open');if(opener)opener.focus({preventScroll:true});});
modal.addEventListener('click',event=>{if(event.target===modal){const r=modal.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)modal.close();}});
previous.addEventListener('click',()=>step(-1));next.addEventListener('click',()=>step(1));
modal.addEventListener('keydown',event=>{if(event.key==='ArrowLeft'){event.preventDefault();step(-1);}if(event.key==='ArrowRight'){event.preventDefault();step(1);}});
photo.addEventListener('touchstart',event=>{startX=event.changedTouches[0].clientX;startY=event.changedTouches[0].clientY;},{passive:true});
photo.addEventListener('touchend',event=>{const dx=event.changedTouches[0].clientX-startX,dy=event.changedTouches[0].clientY-startY;if(startX!==null&&Math.abs(dx)>50&&Math.abs(dx)>Math.abs(dy))step(dx<0?1:-1);startX=startY=null;},{passive:true});
const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('#nav');
function closeMenu(){toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','메뉴 열기');nav.classList.remove('open');}
toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'메뉴 닫기':'메뉴 열기');nav.classList.toggle('open',open);});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',event=>{if(event.key==='Escape')closeMenu();});
document.querySelector('#year').textContent=new Date().getFullYear();
